import numpy as np
print("example for broadcasting:")
v=np.array([1,2,3])
w=np.array([4,5])
print("v=",v)
print("w=",w)
print("outer product of abve vectors:")
print(np.reshape(v,(3,1))*w)
x=np.array([[1,2,3],[4,5,6]])
print("x=",x)
print("resultant matrix after adding the vector x to each row of matrix v:")
print(x+v)
print("example for broadcasting fails:")
print("adding the vector x to each column of marix w will generate an error ")
print("solution:reshape the matrix w then the  result will be:")
print(x+np.reshape(w,(2,1)))
