import numpy as np
a=np.array([1,2,3])
print("one dimensional array a=",a)
b=np.array([[1,2,3],[4,5,6]])
print("two dimensional array b=",b)
print("size of the array:",a.shape)
print ("element at the indices 0,1,2:",a[0],a[1],a[2])
a[0]=5
print("array after changing:",a)
a=np.zeros((2,2))
print("all the elements are 0",a)
b=np.ones((1,2))
print("an array  of all ones:",b)
c=np.full(2,2)
print(" constant array:",c)
d=np.eye(2)
print("a 2*2 identity matrix:",d)
e=np.random.random((2,2))
print("an array with andom values:",e)
